### ISSUE TITLE
Better window position for BetterUI

### ISSUE THREAD

**Issue by HolographicWings** [Eradev/RPGMod#2]
Maybe possible to detect the presence of BetterUI to automatically change ?

![image](https://github.com/Eradev/RPGMod/assets/19623115/c62b0300-df30-43f2-bc67-6ee4b2e87717)
![image](https://github.com/Eradev/RPGMod/assets/19623115/29dd3f01-2fb5-462d-9b44-e39006f206ae)

**Comment by Eradev** [comment]
It's a personal preference so I won't be automating this. It's a one-time setting anyway.
