### ISSUE TITLE
Quests refresh instantly, rewards stack infinitely.

### ISSUE THREAD

**Issue by ClaudeYones** [Eradev/RPGMod#4]
So uh, stumbled upon this funky little bug. I don't think it's any mods that are causing it, hopefully not.

[The game seems to be checking if I've completed a quest every single frame, and proceeds to give me another item over and over again from that one quest.](https://streamable.com/3fe9zq) 

[Same thing happens when I fail a quest, though this time, it's just the notification box for a failed quest that keeps popping up.](https://streamable.com/7kx6ir)

[Except, not actually, because the quest seems to still be tracking the amount of kills required, even after I've already failed the quest, and it proceeds to flood me with the quest reward yet again.](https://streamable.com/uh1mws)

**Comment by Eradev** [comment]
Need a log. I never experienced that so it might be an issue with another mod.

**Comment by ClaudeYones** [comment]
[LogOutput.log](https://github.com/user-attachments/files/16962577/LogOutput.log)
Here's the log, there doesn't seem to be anything in there though. 

[Sending a clip, ](https://streamable.com/0csoca)

[alongside my mod list](https://www.mediafire.com/file/odzc4iwlg322ddu/awawawa_returns_1726052325876.r2z/file), 

if that'll be of any help.

**Comment by Eradev** [comment]
Should be fixed in 3.5.1. Reopen this issue if not the case.
