### ISSUE TITLE
Reworks to vanilla items

### ISSUE THREAD

**Issue by Heshikorin** [Eradev/RPGMod#5]
When using a mod that changes how vanilla items work, the rpgmod no longer sends missions if the mission reward is one of those reworked items

**Comment by Eradev** [comment]
This mod is pretty much in maintenance mode. If you want support for another mod, please submit a PR.

**Comment by Heshikorin** [comment]
Sorry if this is a dumb question, but what's a PR

**Comment by Eradev** [comment]
A pull request.

Essentially I will not be writing code to support another mod myself. If someone else want to code it, they are free to submit their work in a pull request and I'll look at incorporating it.
